version: "3.9"
services:
  # Add the node-js service
  backend:
    # Location to the node.js dockerfile
    build:
      context: ./backend
      # Name of the dockerfile
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      # Bind-mounts configuration
      - ./backend:/src
      # Ignoring any changes made in the "node_modules" folder
      - /app/node_modules
    stdin_open: true

    environment:
      NODE_ENV: development
      DEBUG: backend:*
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      # One-way volume to use node_modules from inside image
      - /app/node_modules
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
